### ISSUE TITLE
checkCaptcha.php console Warning

### ISSUE THREAD

**Issue by totallytotallyamazing** [sdeering/easy-jquery-php-captcha#1]
Hi Sam, I am trying to implement your easy-jquery-php-captcha and keep getting this console error in Firefox Firebug while locally testing it. This warning/error is stopping everything including the dummyScript.php from writing its success message. Can you please help! Thanks, Derek
My Console Warning/error:
     <br /> <b>Warning</b>:  session_start() [<a href='function.session-start'>function.session-start</a>]: Cannot send session cache limiter - headers already sent (output started at /Library/WebServer/Documents/Derek/totallytotallyamazing/easy-jquery-php-captcha-master/php/checkCaptcha.php:1) in <b>/Library/WebServer/Documents/Derek/totallytotallyamazing/easy-jquery-php-captcha-master/php/checkCaptcha.php</b> on line <b>2</b><br />
true

**Comment by sdeering** [comment]
Hi Derek,
You need to use Session Buffer to control the output buffering of the headers.
See here for more info: http://www.php.net/manual/en/function.ob-start.php
Sam

**Comment by totallytotallyamazing** [comment]
Ok Sam, I tried this to my checkCaptcha.php file:

```
<?php
session_start();
bool ob_start ([ callable $output_callback = NULL [, int $chunk_size = 0 [, int $flags = PHP_OUTPUT_HANDLER_STDFLAGS ]]] )
if(isset($_REQUEST['code']))
{
    echo json_encode(strtolower($_REQUEST['code']) == strtolower($_SESSION['captcha']));
}
else
{
    echo 0; // no code
}
?>
```

And now I'm getting this Warning/error:
<br /><b>Parse error</b>:  parse error in <b>/Library/WebServer/Documents/Derek/totallytotallyamazing/easy-jquery-php-captcha-master/php/checkCaptcha.php</b> on line <b>3</b><br />

Can you please offer me a quick fix to my code? Thank you again, Derek

**Comment by totallytotallyamazing** [comment]
I removed all of the spaces / tabs between "session_start();" and "if(isset($_REQUEST['code']))" and that fixed the problem. Here is my code in checkCaptcha.php:

```
<?php
session_start();
if(isset($_REQUEST['code']))
{
echo json_encode(strtolower($_REQUEST['code']) == strtolower($_SESSION['captcha']));
}
else
{
echo 0; // no code
}
?>
```

**Comment by totallytotallyamazing** [comment]
Hi Sam,
Thank you very much for this awesome Captcha, much appreciation! I did manage to get it up and running live on my site. http://www.totallytotallyamazing.com/
Best,
Derek

**Comment by sdeering** [comment]
That's great good work Derek! :)

On Friday, 4 April 2014, Derek Nash notifications@github.com wrote:

> Hi Sam,
> Thank you very much for this awesome Captcha, much appreciation! I did
> manage to get it up and running live on my site.
> http://www.totallytotallyamazing.com/
> Best,
> Derek
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sdeering/easy-jquery-php-captcha/issues/1#issuecomment-39493331
> .

## 

Cheers,
Sam

**Comment by totallytotallyamazing** [comment]
Hi Sam,
Thanks for the compliment by the way... but I am curious and have a generic
question about your captcha since I noticed It does not seem to function in
ie 9. Do you know if it functions in ie 10 or ie 11? And do you care if it
functions in ie 9 or not because I'm not sure if I do... Ha-ha!

On Thu, Apr 3, 2014 at 7:59 PM, Sam Deering notifications@github.comwrote:

> That's great good work Derek! :)
> 
> On Friday, 4 April 2014, Derek Nash notifications@github.com wrote:
> 
> > Hi Sam,
> > Thank you very much for this awesome Captcha, much appreciation! I did
> > manage to get it up and running live on my site.
> > http://www.totallytotallyamazing.com/
> > Best,
> > Derek
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sdeering/easy-jquery-php-captcha/issues/1#issuecomment-39493331>
> > 
> > .
> 
> ## 
> 
> Cheers,
> Sam
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sdeering/easy-jquery-php-captcha/issues/1#issuecomment-39519353
> .

## 

_Derek Nash_
c (646) 265-3773
totallytotallyamazing.com
